### ISSUE TITLE
Incorrect rounding of Line Item with tax

### ISSUE THREAD

**Issue by bjornstromblom** [VirtoCommerce/vc-module-KlarnaCheckout-Euro#1]
[https://github.com/VirtoCommerce/vc-module-KlarnaCheckout-Euro/blob/master/Klarna.PaymentGatewayModule.Web/Managers/KlarnaCheckoutEuroPaymentMethod.cs#L408](url)

If the price of a Line Item with tax has more then two decimals these will be cut and not rounded.

**Comment by bjornstromblom** [comment]
Suggested fix for line 408
`addedItem.Add("unit_price", (int)decimal.Round(lineItem.PlacedPriceWithTax * 100));`

**Comment by asvishnyakov** [comment]
Fixed with 08368d03ee5093be231a61f3240de51be2589168

**Comment by bjornstromblom** [comment]
May i ask way you chose this way of rounding? Is this what's used throughout the platform? As i understand it the standard rounding in .Net is **Rounding to nearest, or banker's rounding** as this is the default way of rounding currency should it maybe be used in this case?

**Comment by tatarincev** [comment]
.NET Math.Round use by default MidpointRounding.ToEven round type (Bank rounding), it is make scene probably because it's a better algorithm. Over the course of many roundings performed, you will average out that all .5's end up rounding equally up and down. This gives better estimations of actual results if you are for instance, adding a bunch of rounded numbers. I would say that even though it isn't what some may expect, it's probably the more correct thing to do.
But in this case we do not have multiple arithmetic operations with rounded values, and MidpointRounding.AwayFromZero more suitable here
